name: Build Android APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        run: |
          # শুধু survival_game ফোল্ডারের ভেতরে gradlew খোঁজা হচ্ছে
          cd survival_game
          chmod +x gradlew
          ./gradlew assembleDebug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Ultimate-Survival-APK
          path: survival_game/app/build/outputs/apk/debug/*.apk
